name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2. Setup Node 20
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Verify Node & NPM version
      - name: Check Node.js & NPM Version
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Build app
      - name: Build React app
        run: CI=false npm run build

      # 6. Deploy to Azure Static Web Apps
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DESERT_0651F5C1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build" # We pass the already-built folder
          api_location: ""      # No API folder
          skip_app_build: true  # ✅ Skip Azure’s internal build process

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DESERT_0651F5C1E }}
          action: "close"

